"""The standing rule template: ``AGENTS.md``.

``lambo/dev-diary/notes/video-shoot.md`` records what actually made an agent
consult memory unprompted: a standing rule it reads (``AGENTS.md``), plus a
working directory where grep answers nothing. That note is explicit that the
MCP server's own ``initialize`` instructions were **not enough on their own
inside a code repository**.

So ``delegate`` refreshes the standing rule in the target repo before
spawning the agent, and the task prompt instructs the agent to read it. The
contractor then consults memory itself, by the mechanism already proven to
work.

The rule is deliberately short and self-contained — it tells the agent what
to do (check Lambo) and when (before any change), without trying to encode
the graph's contents. The graph's contents arrive when the agent calls
``lambo_recall``.
"""

from __future__ import annotations

import logging
import os
from pathlib import Path

log = logging.getLogger(__name__)

STANDING_RULE_TEMPLATE = """\
# Standing Constraints (Auto-generated by Mooshik)

Before making any change, consult Lambo memory for constraints that may
affect this work.

If a Lambo MCP server is configured, use `lambo_recall` with the names of
files and concepts you plan to change.

Respect any canonical constraints with blast radius > 0. Do not ignore them
without explicit instruction from the operator.
"""


def write_standing_rule(repo: str) -> str | None:
    """Write ``AGENTS.md`` to the repo root, returning the path on success.

    If the repo directory does not exist, returns ``None`` and logs a
    warning. An existing ``AGENTS.md`` is overwritten — the content is
    auto-generated and stale rules are worse than fresh ones.
    """
    repo_path = Path(repo)
    if not repo_path.is_dir():
        log.warning("repo %r does not exist; standing rule not written", repo)
        return None

    agents_md = repo_path / "AGENTS.md"
    try:
        agents_md.write_text(STANDING_RULE_TEMPLATE, encoding="utf-8")
        log.info("standing rule written to %s", agents_md)
        return str(agents_md)
    except OSError:
        log.warning("could not write standing rule to %s", agents_md, exc_info=True)
        return None
